# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [4]:
# Import torch
import torch

# Create random tensor
random_tensor = torch.rand(7, 7)
random_tensor

tensor([[0.6993, 0.1932, 0.7956, 0.3021, 0.0194, 0.9108, 0.4503],
        [0.1291, 0.8699, 0.4398, 0.3587, 0.5126, 0.1277, 0.8871],
        [0.5267, 0.6400, 0.5868, 0.1224, 0.6047, 0.6196, 0.7567],
        [0.7462, 0.6425, 0.9806, 0.4306, 0.5949, 0.7173, 0.8059],
        [0.9070, 0.4552, 0.8570, 0.3504, 0.0676, 0.7095, 0.0191],
        [0.0444, 0.2913, 0.0232, 0.6349, 0.7537, 0.6533, 0.8227],
        [0.3549, 0.5205, 0.6339, 0.7346, 0.4721, 0.9804, 0.6413]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [5]:
# Create another random tensor
random_tensor_2 = torch.rand(1, 7)

# Perform matrix multiplication
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.6838],
        [1.7562],
        [1.9269],
        [2.5124],
        [1.8302],
        [1.5201],
        [2.0985]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [6]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors
random_tensor = torch.rand(7, 7)
random_tensor_2 = torch.rand(1, 7)


# Matrix multiply tensors
torch.matmul(random_tensor, random_tensor_2.T)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [7]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [19]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
torch.cuda.is_available()

# Create two random tensors on GPU
random_tensor_1 = torch.rand(2, 3, device='cuda')
random_tensor_2 = torch.rand(2, 3, device='cuda')


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [22]:
# Perform matmul on tensor_A and tensor_B
tensor_3 = torch.matmul(random_tensor_1, random_tensor_2.T)
tensor_3

tensor([[0.2786, 0.7668],
        [0.7343, 0.6102]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [24]:
# Find max
print(f"Max val: {tensor_3.max()}")

# Find min
print(f"Min val: {tensor_3.min()}")

Max val: 0.7667766809463501
Min val: 0.27863210439682007


### 9. Find the maximum and minimum index values of the output of 7.

In [37]:
# Find arg max
print(f"Max idx: {torch.argmax(tensor_3, dim=1)}")


# Find arg min
print(f"Min idx: {torch.argmin(tensor_3, dim=1)}")

Max idx: tensor([1, 0], device='cuda:0')
Min idx: tensor([0, 1], device='cuda:0')


In [33]:
tensor_3[0, 0]

tensor(0.2786, device='cuda:0')

In [30]:
tensor_3[0]

tensor([0.2786, 0.7668], device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [38]:
# Set seed
torch.manual_seed(7)


# Create random tensor
tensor_4 = torch.rand(1, 1, 1, 10)


# Remove single dimensions
tensor_4 = tensor_4.squeeze()


# Print out tensors and their shapes
print(tensor_4)
print(tensor_4.shape)

tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([10])
